CREATE PROC FI_SP_AltBeneficiario
	@Id           BIGINT,
    @NOME          VARCHAR (50),    
	@CPF VARCHAR(11),
	@IDCLINTE BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		NOME = @NOME, 	
		CPF = @CPF,
		@IDCLIENTE = IDCLIENTE
	WHERE Id = @Id AND @IDCLIENTE = IDCLIENTE
END